apiVersion: v1
kind: Service
metadata:
  name: b2hello-service
  namespace: b2apps
spec:
  selector:
    app: b2hello
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP